name: "Unit Tests"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: '.go-version'
        cache: true
    - name: test
      run: make test
